name: openclan-server  # the name of the snap
version: 0  # the version of the snap
summary: A server for gaming clans  # 79 char long summary
description: An open API server for gaming clans # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces

apps:
    openclan-server:
        command: ./bin/openclan-server
        daemon: simple
        plugs: [network, network-bind]
parts:
    openclan:  # Replace with a part name of your liking
        # Get more information about plugins by running
        # snapcraft help plugins
        # and more information about the available plugins
        # by running
        # snapcraft list-plugins
        plugin: go
        source: ./
